name: goguma
description: An IRC client for mobile devices.

publish_to: 'none'

# Build number is the Git commit count, obtained via:
#
#     git rev-list --first-parent --count HEAD
version: 0.6.0+998

environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.1
  shared_preferences: '^2.0.5'
  flutter_linkify: ^6.0.0
  url_launcher: '^6.0.2'
  linkify: ^5.0.0
  sqflite: ^2.0.2
  path: ^1.8.1
  sqflite_common_ffi: ^2.1.0+2
  workmanager: ^0.5.0-dev.8
  flutter_local_notifications: ^17.1.2
  flutter_background: ^1.1.0
  connectivity_plus: ^6.0.2
  shared_preferences_android: ^2.0.12
  # TODO: replace "webcrypto" with the "cryptography" package once they have a
  # pure Dart Ecdh.p256 implementation
  webcrypto: ^0.5.3
  firebase_core: ^2.1.0
  firebase_messaging: ^14.0.2
  app_links: ^6.1.1
  unifiedpush: ^5.0.0
  sentry: ^7.2.0
  share_plus: ^9.0.0
  flutter_flipped_autocomplete: ^1.0.0
  scrollable_positioned_list: ^0.3.5
  html: ^0.15.2
  geolocator: ^11.0.0
  image_picker: ^1.0.4
  mime: ^1.0.4
  file_selector: ^1.0.1
  flutter_apns_only: ^1.6.0
  share_handler: ^0.0.21

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
