name: goguma
description: An IRC client for mobile devices.

publish_to: 'none'

# Build number is the Git commit count, obtained via:
#
#     git rev-list --first-parent --count HEAD
version: 0.7.0+1079

environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.1
  shared_preferences: '^2.0.5'
  flutter_linkify: ^6.0.0
  url_launcher: '^6.0.2'
  linkify: ^5.0.0
  sqflite: ^2.0.2
  path: ^1.8.1
  sqflite_common_ffi: ^2.1.0+2
  workmanager: ^0.5.0-dev.8
  flutter_local_notifications: ^17.1.2
  # TODO: drop Git checkout once this is merged:
  # https://github.com/JulianAssmann/flutter_background/pull/89
  flutter_background:
    git:
      url: https://github.com/emersion/flutter_background.git
      ref: f3437614c405bac5023f8b58574d4b6a77c610f0
  connectivity_plus: ^6.0.2
  shared_preferences_android: ^2.0.12
  # TODO: replace "webcrypto" with the "cryptography" package once they have a
  # pure Dart Ecdh.p256 implementation
  webcrypto: ^0.5.7
  firebase_core: ^2.1.0
  firebase_messaging: ^14.0.2
  app_links: ^6.1.1
  unifiedpush: ^5.0.0
  sentry: ^8.2.0
  share_plus: ^10.0.1
  flutter_flipped_autocomplete: ^1.0.0
  scrollable_positioned_list: ^0.3.5
  html: ^0.15.2
  geolocator: ^13.0.1
  image_picker: ^1.0.4
  mime: ^1.0.4
  file_selector: ^1.0.1
  flutter_apns_only: ^1.6.0
  share_handler: ^0.0.21
  dynamic_color: ^1.7.0

dependency_overrides:
  # TODO: drop once this is merged:
  # https://github.com/UnifiedPush/flutter-connector/pull/152
  unifiedpush_android:
    git:
      url: https://github.com/emersion/UnifiedPush-flutter-connector.git
      ref: 1c2861f9e1e744a5644efdcad957d0a6a3aac733
      path: unifiedpush_android

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
