name: goguma
description: An IRC client for mobile devices.

publish_to: 'none'

# Build number is the Git commit count, obtained via:
#
#     git rev-list --first-parent --count HEAD
version: 0.4.1+712

environment:
  sdk: '>=2.14.0 <3.0.0'
  flutter: ^3.3.0

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.1
  shared_preferences: '^2.0.5'
  flutter_linkify: '^5.0.0'
  url_launcher: '^6.0.2'
  linkify: '^4.0.0'
  sqflite: ^2.0.2
  path: ^1.8.1
  sqflite_common_ffi: ^2.1.0+2
  workmanager: ^0.5.0-dev.8
  flutter_local_notifications: ^12.0.3
  flutter_background: ^1.1.0
  connectivity_plus: ^3.0.2
  flutter_typeahead: ^4.0.0
  shared_preferences_android: ^2.0.12
  # TODO: replace "webcrypto" with the "cryptography" package once they have a
  # pure Dart Ecdh.p256 implementation
  webcrypto: ^0.5.3
  firebase_core: ^2.1.0
  firebase_messaging: ^14.0.2
  app_links: ^3.2.0
  unifiedpush: ^4.0.1

dev_dependencies:
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
