name: goguma
description: An IRC client for mobile devices.

publish_to: 'none'

# Build number is the Git commit count, obtained via:
#
#     git rev-list --first-parent --count HEAD
version: 0.2.0+516

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ^2.0.0

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.1
  shared_preferences: '^2.0.5'
  flutter_linkify: '^5.0.0'
  url_launcher: '^6.0.2'
  linkify: '^4.0.0'
  sqflite: ^2.0.2
  path: ^1.8.1
  sqflite_common_ffi: ^2.1.0+2
  workmanager: ^0.5.0-dev.8
  flutter_local_notifications: ^9.4.0
  flutter_background: ^1.1.0
  connectivity_plus: ^2.2.1
  flutter_typeahead: ^3.2.4

dev_dependencies:
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true
